language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - "pip install setuptools==15.1"
    - "pip install -r requirements/dev.txt"
# command to run tests
script:
    - "nosetests"
